### ISSUE TITLE
Contrast

### ISSUE THREAD

**Issue by cantao** [rougier/nano-emacs#10]
First of all, let me thank you for what I can only call an work of art!

Second, is it possible to easily adjust the constrast? Some colors are too similar for my eyes...

**Comment by rougier** [comment]
Thanks. For the color, you edit either the nano-theme-light or nano-theme-dark where all the (n=0) colors are defined. To help you, you can also have a look a nano-colors.el that provide some optional helper functions

**Comment by cantao** [comment]
Ah, I see. I can barely read Elisp, but I saw a `hue` variable somewhere that hinted me of something automatic. I'll dig into it. Thank you very much!
