### ISSUE TITLE
mu4e-moved-face issue

### ISSUE THREAD

**Issue by OrionRandD** [rougier/nano-emacs#105]
I had this Emacs Doom *Warnings* buffer
complaning about "mu4e-moved-face"

Error in private config: config.el, (error Invalid face mu4e-moved-face)
To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

somo more info

 $  rg 'mu4e-moved-face'
repos/doom-nano-testing/nano-theme.el
527:    (set-face 'mu4e-moved-face                         'nano-face-faded)

repos/alect-themes/alect-themes.el
1333:         (mu4e-moved-face                ((,c :foreground ,(gc 'blue+2))))

repos/modus-themes/modus-themes.el
6612:    `(mu4e-moved-face ((,class :inherit modus-themes-slant :foreground ,yellow)))

How do I fix this?

**Comment by OrionRandD** [comment]
> I had this Emacs _Warnings_ buffer complaning about "mu4e-moved-face"
> 
> Error in private config: config.el, (error Invalid face mu4e-moved-face) To ensure normal operation, you should investigate and remove the cause of the error in your initialization file. Start Emacs with the ‘--debug-init’ option to view a complete error backtrace.
> 
> somo more info
> 
> $ rg 'mu4e-moved-face' repos/doom-nano-testing/nano-theme.el 527: (set-face 'mu4e-moved-face 'nano-face-faded)
> 
> repos/alect-themes/alect-themes.el 1333: (mu4e-moved-face ((,c :foreground ,(gc 'blue+2))))
> 
> repos/modus-themes/modus-themes.el 6612: `(mu4e-moved-face ((,class :inherit modus-themes-slant :foreground ,yellow)))
> 
> How do I fix this?

more info from the debugger:

Debugger entered--Lisp error: (error "Invalid face" mu4e-moved-face)
  internal-set-lisp-face-attribute(mu4e-moved-face :family unspecified 0)
  set-face-attribute(mu4e-moved-face nil :foreground unspecified :background unspecified :family unspecified :slant unspecified :weight unspecified :height unspecified :underline unspecified :overline unspecified :box unspecified :inherit nano-face-faded)
  set-face(mu4e-moved-face nano-face-faded)
  #f(compiled-function () #<bytecode 0x1562484993dd>)()
  eval-after-load(mu4e #f(compiled-function () #<bytecode 0x1562484993dd>))
  nano-theme--mu4e()
  nano-theme()
  #<subr eval-buffer>(#<buffer  *load*> nil "/home/vagner/.emacs.d/.local/straight/build-27.1/n..." nil t)
  apply(#<subr eval-buffer> (#<buffer  *load*> nil "/home/vagner/.emacs.d/.local/straight/build-27.1/n..." nil t))
  eval-buffer(#<buffer  *load*> nil "/home/vagner/.emacs.d/.local/straight/build-27.1/n..." nil t)  ; Reading at buffer position 359
  load-with-code-conversion("/home/vagner/.emacs.d/.local/straight/build-27.1/n..." "/home/vagner/.emacs.d/.local/straight/build-27.1/n..." nil t)
  require(load-nano)
  eval((require 'load-nano) nil)
  elisp--eval-last-sexp(nil)
  #f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0x1fe91b75fc2d>)(nil)
  apply(#f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0x1fe91b75fc2d>) nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

**Comment by OrionRandD** [comment]
I use doom emacs...

**Comment by rougier** [comment]
Sorry for the late answer. You might give a try to [nano-theme](https://github.com/rougier/nano-theme) which is available on ELPA and shoudl fix the problem because it is now a regular theme.

**Comment by OrionRandD** [comment]
thx :)
