### ISSUE TITLE
Font too thin

### ISSUE THREAD

**Issue by azzamsa** [rougier/nano-emacs#106]
Hi. 

Using the config below I got nano-emacs working on my side. but the font is too thin and hardly readable. 
Are the looks below are expected?

![image](https://user-images.githubusercontent.com/17734314/144697998-2b67ce02-c79e-4f12-81c4-61df0018456d.png)

``` emacs-lisp

(straight-use-package
  '(nano-emacs :type git :host github :repo "rougier/nano-emacs"))

(use-package nano-base-colors :straight nil)
(use-package nano-colors :straight nil)
(use-package nano-theme-light
  :straight nil
  :config
  (nano-theme-set-light))

(use-package nano-faces
  :straight nil
  :config
  (nano-faces))

(use-package nano-theme
  :straight nil
  :config
  (nano-theme))

(use-package nano-modeline
  :straight nil)
```

I have both Fira Code and Roboto installed.

Sistem Information:

```
GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0) of 2021-12-01
c13b49a110 (HEAD -> master, origin/master, origin/HEAD) 2 days ago update_autogen: Remove deprecated -I flag (Stefan Kangas)

OS: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-9-amd64 x86_64
```

This is the font looks that I use previously (comfortable for me):

![image](https://user-images.githubusercontent.com/17734314/144698104-2ca5e8aa-2d2f-49ff-b9e6-d3208ae58fd6.png)

Compared to nano:

![image](https://user-images.githubusercontent.com/17734314/144698265-fb7c8a40-2c8c-4f5c-a27e-77d6db98689b.png)

Thanks for nano!

**Comment by azzamsa** [comment]
I successfully changed some part of the font from light to medium. Both changed the font weight for comment and mode-line.
But I am still stuck changing the default font weight.

```diff
@@ -211,11 +211,11 @@ background color that is barely perceptible."
 
   (set-face-attribute 'nano-face-salient nil
                       :foreground nano-color-salient
-                      :weight 'light)
+                      :weight 'medium)
 
   (set-face-attribute 'nano-face-faded nil
                       :foreground nano-color-faded
-                      :weight 'light)
+                      :weight 'medium)
 ```
 
 My only solution right now is using:
 
 ```lisp
 (setq default-frame-alist '((font . "Fira Code 15")))
```

But indeed it will impact every font faces.

**Comment by rougier** [comment]
You can actually select the font through customize: `M-x customize-group nano-theme-fonts`. This will work for the default font. You can also customize nano-theme and tell nano to not set up fonts at all.

**Comment by azzamsa** [comment]
Thank you.

**Comment by rougier** [comment]
By the way, what is your OS?

**Comment by azzamsa** [comment]
```
