### ISSUE TITLE
Modeline doesn't span width of frame (emacs 29)

### ISSUE THREAD

**Issue by jdm204** [rougier/nano-emacs#109]
Hi, big fan of your emacs projects!

Building emacs from master and running `emacs -q -l nano.el`, emacs looks like this:

![nano-emacs-29-modeline](https://user-images.githubusercontent.com/34479575/147763102-21e488d0-efff-4daf-9a4d-b27913d8921c.png)

with the modeline too short - it stays that proportion when I change the size of the frame.

**Comment by xiaoxinghu** [comment]
Same on 28.0.60 for me.

![Uploading CleanShot 2021-12-31 at 13.22.57@2x.png…]()

**Comment by jdm204** [comment]
Okay, I tried the `emacs-gtk` deb package (1:27.1+1-3ubuntu3) and got the same issue:

![nano_modeline-27](https://user-images.githubusercontent.com/34479575/147820595-ab7029a2-fe7a-456b-a12b-8c5ed444b368.png)

Not sure this will be helpful as @xiaoxinghu seems to be on macOS, but these are my system details:
```
➜ screenfetch && echo $XDG_SESSION_TYPE
                          ./+o+-       
                  yyyyy- -yyyyyy+      OS: Ubuntu 21.10 impish
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.13.0-22-generic
           .++ .:/++++++/-.+sss/`      Uptime: 2d 16h 42m
         .:++o:  /++++++++/:--:/-      Packages: 2418
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 5.1.8
       .:+o:+o/.          `+sssoo+/    Resolution: 3840x2400
  .++/+:+oo+o:`             /sssooo.   DE: GNOME 40.0
 /+++//+:`oo+o               /::--:.   WM: Mutter
 \+/+o+++`o++o               ++////.   WM Theme: Adwaita
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Yaru [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: Yaru
        \+.++o+o``-````.:ohdhhhhh+     Font: Ubuntu 11
         `:o+++ `ohhhhhhhhyo++os:      Disk: 271G / 938G (31%)
           .o:`.syhhhhhhh/.oo++o`      CPU: Intel Core i7-1065G7 @ 8x 3.9GHz [51.0°C]
               /osyyyyyyo++ooo+++/     GPU: Intel Corporation Iris Plus Graphics G7 (rev 07)
                   ````` +oo+++o\:     RAM: 6063MiB / 15583MiB
                          `oo++.
wayland
```

**Comment by jdm204** [comment]
Just realised I didn't have Roboto *Mono* installed; upon installation the modeline behaves as it should on emacs 27.1 and compiled from master, even if the default font is changed back via  `customize-face` - @xiaoxinghu you probably have the same issue, closing this.

**Comment by rougier** [comment]
The modeline will probably not work with a non-monospaced font.

**Comment by xiaoxinghu** [comment]
@jdm204 yes, confirmed everything works after installing Roboto Mono.
