### ISSUE TITLE
Broken nano-help

### ISSUE THREAD

**Issue by brongulus** [rougier/nano-emacs#110]
Currently I'm using nano emacs with straight and invoking nano-help results in erroneous behaviour, invoking nano-help from M-x results in:
> Wrong type argument: stringp, nil

I think it might be due to how the function nano-help is defined and dependent on load-path and how nano-emacs hardcodes the load-path variable to call nano-help from `./` the nano-help directory. 

Another thing that I observed while checking for `load-path`'s value is that it has `"/Users/rougier/Documents/GitHub/nano-emacs"` explicitly mentioned so I think that nano-help is dependent on that hardcoded path? Would that be a correct assumption?

The only possible way to open nano-help right now is to manually go to the `$EMACSDIR/straight/repos/nano-emacs` and then call the function.

**Comment by rougier** [comment]
Thanks for the report and the fix. I've answered in the PR.
