### ISSUE TITLE
Corfu annotation alignment

### ISSUE THREAD

**Issue by Artawower** [rougier/nano-emacs#114]
Is is possible to fix corfu annotations? 
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/16963833/152660231-424e5c6c-9f7d-477b-a9e4-29400ff82a28.png">
This problem appears only with nano theme
Without nano-emacs
<img width="762" alt="image" src="https://user-images.githubusercontent.com/16963833/152660315-d2031306-92f9-48b6-b7f5-c4d45d19b4bc.png">

**Comment by rougier** [comment]
I'm not sure what could be the reasons. Can you try nano-theme (available on ELPA) stand-alone to see if is fails in the same way ?

**Comment by Artawower** [comment]
The problem was in the font, after changing it, everything was fine. Thanks
