### ISSUE TITLE
Wierd colors when on TTY dark theme

### ISSUE THREAD

**Issue by tanaxer01** [rougier/nano-emacs#119]
Opening Nano emacs in the tty mode with the dark mode shows the theme in a greenish way 
![image](https://user-images.githubusercontent.com/2672077/161896651-bd27b1d7-61a6-4b53-a3d6-36453abc8f5a.png)
Tried changing the base theme of my terminal but nothing changed.

Any clue of what might be causing this issue??

**Comment by rougier** [comment]
It mostly depends on your terminal capability. Do you know if it's truecolor and if you can set colors ?

**Comment by tanaxer01** [comment]
I fixed it! The problem was that truecolor was disabled by default

Thanks for the help!
