### ISSUE TITLE
Proposal: Add path of file concateded or directory in modeline

### ISSUE THREAD

**Issue by vijaypanchalr3** [rougier/nano-emacs#120]
![Screenshot from 2022-04-14 16-23-24](https://user-images.githubusercontent.com/72692300/163377423-2d2dcac1-7f61-4734-a508-8f623e8ec148.png)
like showed in screenshot

**Comment by vijaypanchalr3** [comment]
![Screenshot from 2022-04-14 16-23-24](https://user-images.githubusercontent.com/72692300/163377423-2d2dcac1-7f61-4734-a508-8f623e8ec148.png)
like showed in screenshot

**Comment by rougier** [comment]
You mean for prog-mode ? Note that you can rewrite any specific mode modeline adapting code from other modes
