### ISSUE TITLE
[Bug] Org-mode headings in source code blocks override indentation and formatting from src code block

### ISSUE THREAD

**Issue by wakatara** [rougier/nano-emacs#136]
Sorry, another bug report. Pretty sure this is nano-emacs since I disabled my mods and org-bullets.

It appears that when you have org-mode headings inside a source code block, nano overrides the formatting of the source code block with org-mode formatting (and left indents everything rather than honouring the source code block format and indent level.

**Steps to reproduce**

Paste the following into an org-mode document under nano. 

```
#+begin_src elisp

("r" "Rez" plain "%?"
	 :target (file+head "~/Documents/org/refs/rez/${slug}.org"
"#+TITLE: ${title}
#+CREATED: %u
#+MODIFIED:

* ${title}
:PROPERTIES:
:Type:
:Start:
:Fin:
:Killed:
:Rating:
:Digested:
:Creator:
:URL:
:END:

** Actions

** Key Ideas
...
#+end_src
```

**What Happens**

Org-mode formatting and indenting overrides the source code block. Bullets and left indents heavily.

**What Should Happen**

nano should honour the source code block formatting and syntax highlighting.

*(as always, thanks for doing such an amazing job on nano. It really does make my emacs experience soooo much better)* 😍

**Comment by wakatara** [comment]
Sorry, one other thing I should mention, the overall document "sees" those org-mode headings as proper headings in terms of fold/reveal etc etc... so really messes with long documents with any code in them that has a '*' in the starting line.

**Comment by wakatara** [comment]
Hmmm... also just noticed that I get this Warning as well :

``` bash
 Warning (org-element-cache): org-element--cache: Org parser error in 2023-01-16-emacs-gtd-and-crm-flow-revisited.org::#<marker at 47012 in 2023-01-16-emacs-gtd-and-crm-flow-revisited.org>
  The error was: (error "Invalid search bound (wrong side of point)")
 Backtrace:
nil
 Please report this to Org mode mailing list (M-x org-submit-bug-report).
```

**Comment by wakatara** [comment]
This is apparently nothing to do with nano and an actual issue with the way org-mode parses docs. You are apparently supposed to add a comma in front of lines inside blocks like this. Was surprised to find this out and unfortunately think this was a bad call on the org-mode syntax front by the devs. But hey... 

closing ticket.

**Comment by rougier** [comment]
Thanks for the report. For the actual theme, you might want to give a try to nano-theme which is on elpa and is a standard theme that be customized more easily.
