### ISSUE TITLE
Changing the default to Nano Dark?

### ISSUE THREAD

**Issue by haziz** [rougier/nano-emacs#138]
Maybe I missed it, but I am unable to figure out how emacs should start and default to the dark theme. By copying the nano-emacs repository into my .emacs.d folder and with cutting and pasting of the contents of nano.el into my init.el file, I have managed to get Emacs to start using the light theme. I even figured out how to change the default font size on my HiDPI scree. I would prefer if it would default to the dark theme, but even after an hour of perusing the emacs lisp files and some tinkering I am unable to convince it to start in dark mode.

While I am somewhat comfortable with Scheme and Common Lisp, my grasp of Emacs Lisp is tenuous at best, please be very explicit and clear about what I need to do.

Thanks.

**Comment by rougier** [comment]
Did you try to modify (customize) `nano-theme-var`?

**Comment by haziz** [comment]
Which Emacs Lisp includes the nano-theme-var variable?

Thanks.

**Comment by rougier** [comment]
[nano-theme.el](https://github.com/rougier/nano-emacs/blob/master/nano-theme.el) but you can also customize the variable and save it in along your other customization.

**Comment by Midnight1938** [comment]
> Did you try to modify (customize) `nano-theme-var`?

Ive tried `(steq nano-theme-var dark)`, which gives an error. And setting it to 0-9 does nothing

**Comment by rougier** [comment]
Can you try `(setq nano-theme-var 'dark)` ? Else you can also customize the nano-theme group. Last option is to use the ELPA nano-theme.

**Comment by Midnight1938** [comment]
> Can you try `(setq nano-theme-var 'dark)` ? Else you can also customize the nano-theme group. Last option is to use the ELPA nano-theme.

I have been able to set the theme to dark.
But must also use nano-toggle-theme fir every client instance to "initialize" the nano visuals

**Comment by rougier** [comment]
How did you do it in the end?

**Comment by Midnight1938** [comment]
> How did you do it in the end?

> How did you do it in the end?

I made the nano initializer something like this:
```elisp
(require 'nano-layout)
(require 'nano-faces)
(nano-faces)
```
And its now able to pick up new themes and toggle itself.


[complete config](https://gitlab.com/Midnight1938/arohan-emacs/-/blob/main/init.org) if that helps
