### ISSUE TITLE
cursor stays visible in first window when switching to the second window

### ISSUE THREAD

**Issue by YassinRian** [rougier/nano-emacs#155]
I am using ace-window ...opening a new vertical or horizontal window and switching to one of those keeps the cursor visible (empty box) in the first window. Is this a bug or known to you? by the way I switched off Nano and used other themes and this behaviour doesnt occur
thanks in advance

**Comment by rougier** [comment]
What is the value of `cursor-in-non-selected-windows` (with and without nano theme) ?

**Comment by YassinRian** [comment]
Hi Rougier,
Sorry for my late response ..indeed cursor-in-non-selected-windows should be nil to prevent this behaviour. Thanks!
