### ISSUE TITLE
How to insert the code to make `nano-modeline` which can show the time?

### ISSUE THREAD

**Issue by HoyiousXBFamily** [rougier/nano-emacs#159]
This is my code: 

```elisp
(setq display-time-format "%Y-%m-%d %H:%M %A")
(display-time-mode 1)
```

I just wanted to show the time in the nano-modeline, but it didn't work. Could I know what can I do?

**Comment by rougier** [comment]
Best is to use nano-modeline which is on ELPA.

**Comment by HoyiousXBFamily** [comment]
Thank you, sir.
