### ISSUE TITLE
tab-bar support?

### ISSUE THREAD

**Issue by Cerebus** [rougier/nano-emacs#161]
It's easy enough to `set-face` for tab-bar faces, but the separation between the mode-line and the tab-bar looks awful.

![image](https://github.com/user-attachments/assets/3c4ffe2a-6ae8-410d-bb11-19edda830bff)

Any ideas what can be done about this?

**Comment by Cerebus** [comment]
Closing out; seems this project is OBE anyway, and after poking around it doesn't look like there's any way to make tab-bar play nicer with internal-border-width.  For now I just colored up tab-bar faces to minimize the ugly.  I also switched to telephone-line over nano-modeline, and it exposes the line height so mayhap there's something to do there.

**Comment by rougier** [comment]
Sorry for late anwer. You have some code here:
https://gist.github.com/rougier/4b82935e2735664516018828da24a84f
https://gist.github.com/rougier/8b79c9f2178e9cbebbeb41b50478a19d
