### ISSUE TITLE
mode-line-position on pdf-view-mode

### ISSUE THREAD

**Issue by jacksonbenete** [rougier/nano-emacs#2]
Would be good to show the current page number when reading pdfs.
It's easy to get lost without an indicator.

There is a variable called `mode-line-position` that on `pdf-view-mode` will return something like "P 3/33" for the current-page/total-pages.

You can see the actual code on the [pdf-tools page](https://github.com/politza/pdf-tools/blob/master/lisp/pdf-view.el), but I think this is all what's needed:

```elisp
(setq-local mode-line-position
              '(" P" (:eval (number-to-string (pdf-view-current-page)))
                ;; Avoid errors during redisplay.
                "/" (:eval (or (ignore-errors
                                 (number-to-string (pdf-cache-number-of-pages)))
                               "???"))))
```

I'm trying to solve this problem, still not much progress but might not be something hard to do.
I would not know the best style to present this in the mode-line as I'm not good at design and the project is your's.
But probably might be the case to replace `(position    (format-mode-line "%l:%c"))` with this value, since in a pdf page the line:column will be always as "1:0" as far as I know, so in this case it wouldn't be necessary to show the line:column.

**Comment by rougier** [comment]
Good point. You can tweak the modeline (nano-modelien.el)[https://github.com/rougier/nano-emacs/blob/master/nano-modeline.el] by adding a function for detecting the pdf mode and another one to tell what to display in the header line. Could you make a PR?

**Comment by jacksonbenete** [comment]
Sure, I'm glad I can help.
I can send a PR with this implementation:


![image](https://user-images.githubusercontent.com/2954722/100651630-7c2b8c00-3324-11eb-99c7-6fccf8c260a9.png)


I'm just changing the `line:column` to `current-page/number-of-pages` for the "secondary" parameter, the rest of the function is exact the same as the `nano-modeline-default-mode` function.

But before I would like to clarify the best approach for the status bar.
I'm not sure if we should keep the "RO" status, since that's not exactly true.
Although I can't "write" on the PDF, I can highlight and save the file, modifying it.


![image](https://user-images.githubusercontent.com/2954722/100651502-48e8fd00-3324-11eb-90c9-f3c6d9d02362.png)


I will wait for your decision and then I will send the PR.

**Comment by rougier** [comment]
Perfect ! By the way, from your screenshot, I just discovered you can highlight test in PDF mode...
