### ISSUE TITLE
Performance question (byte compile)

### ISSUE THREAD

**Issue by ericdallo** [rougier/nano-emacs#20]
I'm using emacs nativecomp branch (emacsGcc) with doom-emacs, and it's really fast. One of doom-emacs features is byte-compile elisp files from packages to have a better performance, is this supported here? If not, WDYT about adding this kind of support?

**Comment by rougier** [comment]
I'm not sure how to do that in fact. Do you have some pointers?

**Comment by mrzor** [comment]
I'm not a doom-emacs user, but FOMO is kicking in and I ... want this faster native compiling Emacs. I'm willing to give this a shot.

**Comment by rougier** [comment]
Note that startup is already quite fast, at least on my machine (0.25 seconds). But I suspect the displayed time (`emacs-init-time`) is not the best way to measure initialization time.
