### ISSUE TITLE
Additional requirements: ivy / counsel

### ISSUE THREAD

**Issue by duianto** [rougier/nano-emacs#22]
The readme requirements, state that only Emacs and fonts are required:
https://github.com/rougier/nano-emacs#requirements
>You need a recent version of GNU Emacs and to have the Roboto Mono and Fira Code fonts installed on your system. There are no other dependencies.

After downloading the repository ZIP.
Extracting it and running:
```
runemacs -q -l nano.el
```
It first complained about the font:
>frame-notice-user-settings: Font ‘Roboto Mono:style=Light:size=14’ is not defined

(understandable since the font wasn't installed)

After installing the `Roboto Mono` font:
https://fonts.google.com/specimen/Roboto+Mono
and restarting Emacs with nano.el.

### Issue:
Now it says:
>eval-buffer: Symbol’s function definition is void: ivy-mode

#### Source:
https://github.com/rougier/nano-emacs/blob/77b81d0c07abe2b0b18c9004eb7b8f2209b9e508/nano-counsel.el#L41

And pressing: `M-x`
shows:
>command-execute: Wrong type argument: commandp, counsel-M-x

https://github.com/rougier/nano-emacs/blob/77b81d0c07abe2b0b18c9004eb7b8f2209b9e508/nano-counsel.el#L34

### A possible solution
Maybe the nano-counsel requirement should be commented out by default.
https://github.com/rougier/nano-emacs/blob/709710127cbefb2e3d3ea774a3b0658e75d3edab/nano.el#L69-L71

Since it disables `M-x`.

System:
- GNU Emacs 27.1 (build 1, x86_64-w64-mingw32) of 2020-08-21
- Windows 10 2004

**Comment by rougier** [comment]
Thanks. You're right, we can comment it out. Can you make a PR?
