### ISSUE TITLE
Invalid face, message-cited-text-1

### ISSUE THREAD

**Issue by mkesslerct** [rougier/nano-emacs#3]
I like very much the look and feel of emacs nano. But I get the following error when loading with require. It may be something I am doing wrong when loading the nano-dark-theme module? 
Thanks for any help, and emacs-nano looks awesome, congrats!

`Debugger entered--Lisp error: (error "Invalid face" message-cited-text-1)`

 `internal-set-lisp-face-attribute(message-cited-text-1 :family unspecified 0)`

 `set-face-attribute(message-cited-text-1 nil :foreground unspecified :background unspecified :family unspecified :slant unspecified :weight unspecified :height unspecified :underline unspecified :overline unspecified :box unspecified :inherit nano-face-faded)`
  
`set-face(message-cited-text-1 nano-face-faded)`
 `(lambda nil (set-face (quote message-cited-text) (quote nano-face-faded)) (set-face (quote message-cited-text-1) (quote nano-face-faded)) (set-face (quote message-cited-text-2) (quote nano-face-faded)) (set-face (quote message-cited-text-3) (quote nano-face-faded)) (set-face (quote message-cited-text-4) (quote nano-face-faded)) (set-face (quote message-header-cc) (quote nano-face-default)) (set-face (quote message-header-name) (quote nano-face-strong)) (set-face (quote message-header-newsgroups) (quote nano-face-default)) (set-face (quote message-header-other) (quote nano-face-default)) (set-face (quote message-header-subject) (quote nano-face-salient)) (set-face (quote message-header-to) (quote nano-face-salient)) (set-face (quote message-header-xheader) (quote nano-face-default)) (set-face (quote message-mml) (quote nano-face-popout)) (set-face (quote message-separator) (quote nano-face-faded)))()`

`eval-after-load(message (lambda nil (set-face (quote message-cited-text) (quote nano-face-faded)) (set-face (quote message-cited-text-1) (quote nano-face-faded)) (set-face (quote message-cited-text-2) (quote nano-face-faded)) (set-face (quote message-cited-text-3) (quote nano-face-faded)) (set-face (quote message-cited-text-4) (quote nano-face-faded)) (set-face (quote message-header-cc) (quote nano-face-default)) (set-face (quote message-header-name) (quote nano-face-strong)) (set-face (quote message-header-newsgroups) (quote nano-face-default)) (set-face (quote message-header-other) (quote nano-face-default)) (set-face (quote message-header-subject) (quote nano-face-salient)) (set-face (quote message-header-to) (quote nano-face-salient)) (set-face (quote message-header-xheader) (quote nano-face-default)) (set-face (quote message-mml) (quote nano-face-popout)) (set-face (quote message-separator) (quote nano-face-faded))))`

 `eval-buffer(#<buffer  *load*-711198> nil "c:/Users/mkess/.emacs.d/lisp/nano-emacs/nano-theme.el" nil t)  ; Reading at buffer position 14093`
 `load-with-code-conversion("c:/Users/mkess/.emacs.d/lisp/nano-emacs/nano-theme.el" "c:/Users/mkess/.emacs.d/lisp/nano-emacs/nano-theme.el" nil t)`
  `require(nano-theme)`
 `eval-buffer(#<buffer  *load*-892567> nil "c:/Users/mkess/.emacs.d/lisp/nano-emacs/nano-theme-dark.el" nil t)  ; Reading at buffer position 1311`
 `load-with-code-conversion("c:/Users/mkess/.emacs.d/lisp/nano-emacs/nano-theme-dark.el" "c:/Users/mkess/.emacs.d/lisp/nano-emacs/nano-theme-dark.el" nil t)`
 `require(nano-theme-dark)`
  `eval-buffer(#<buffer  *load*> nil "c:/Users/mkess/.emacs.d/init.el" nil t)  ; Reading at buffer position 3190`
 ` load-with-code-conversion("c:/Users/mkess/.emacs.d/init.el" "c:/Users/mkess/.emacs.d/init.el" t t)
  load("c:/Users/mkess/.emacs.d/init" t t)`d

**Comment by rougier** [comment]
Thanks for the report. What is your emacs version? And does this happen right at the start ?

**Comment by mkesslerct** [comment]
Hi! It is GNU Emacs 26.3 on Windows 10 (build 1, x86_64-w64-mingw32). Thanks!

**Comment by mkesslerct** [comment]
And I forgot to indicate that indeed it happens right at the start

**Comment by rougier** [comment]
Most certainly I try to define a face `message-cited-text-1` that is only define in Emacs 27.0. Can ou try to comment the line in `nano-theme.el`to check if it solved the problem (and probably other `message-cited-text-xxx`)

**Comment by jacksonbenete** [comment]
That's odd because I'm on Emacs 26.3 and I'm receiving no error message.

I'm loading with just a `load-path` and a `require`.
```
(add-to-list 'load-path "~/.emacs.d/nano-emacs")
(require 'nano-layout)
;; (require 'nano-theme-dark)
(require 'nano-theme-light)
(require 'nano-modeline)
(require 'nano-splash)
(require 'nano-help)
```
Both light and dark themes shows no error message, but I'm on Linux.

**Comment by mkesslerct** [comment]
To comment out the four lines message-cited-text-[1-4], indeed makes the error disappear
Thanks! Anyway I will upgrade emacs to 27.

**Comment by jacksonbenete** [comment]
Ok, correcting what I've said.
Indeed, there is no error for just starting Emacs for me, but the same error was preventing `magit` to work.
Then, the following solved the problem for magit, it will probably solve for any other related problem if indeed it was introduced in version "27.0".

```lisp
;; Message
(with-eval-after-load 'message
  (set-face 'message-cited-text                      'nano-face-faded)
  (unless (version< emacs-version "27.0")
    (set-face 'message-cited-text-1                  'nano-face-faded)
    (set-face 'message-cited-text-2                  'nano-face-faded)
    (set-face 'message-cited-text-3                  'nano-face-faded)
    (set-face 'message-cited-text-4                 'nano-face-faded))
  (set-face 'message-header-cc                     'nano-face-default)
  (set-face 'message-header-name                    'nano-face-strong)
  (set-face 'message-header-newsgroups             'nano-face-default)
  (set-face 'message-header-other                  'nano-face-default)
  (set-face 'message-header-subject                'nano-face-salient)
  (set-face 'message-header-to                     'nano-face-salient)
  (set-face 'message-header-xheader                'nano-face-default)
  (set-face 'message-mml                            'nano-face-popout)
  (set-face 'message-separator                       'nano-face-faded))
```
