### ISSUE TITLE
Suggestions partially cut off when using ispell

### ISSUE THREAD

**Issue by dixius99** [rougier/nano-emacs#38]
Not exactly sure I would call this an "issue", but I've been using parts from nano-emacs, and when I use `ispell`, the bottom row of suggestions is cut off around half way. It doesn't matter how many rows of suggestions are provided. It's always the last row that is partially cut off. I can still read all of the suggestions, so not a big deal, but I was wondering if there is a setting I could change to have all of the suggestions display.

I don't use all of the modules, so maybe this wouldn't happen if I used some of the others? These are the ones I'm using:

- nano-base-colors
- nano-faces
- nano-modeline

Here is a screen of what I see:

<img width="897" alt="Screen Shot 2020-12-24 at 3 02 33 PM" src="https://user-images.githubusercontent.com/1924526/103105266-b07c2a80-45fa-11eb-82c0-a2b2132a297a.png">

**Comment by rougier** [comment]
Can you try to set `window-resize-pixelwise` to t in you config? I think the reason for the cut line is the vertical spaces I added in the header line (see modeline code).

**Comment by dixius99** [comment]
Hmm... `(setq window-resize-pixelwise t)` didn't seen to change anything for me. Interestingly, it also only appears to be the first typo. All subsequent typos seem to have enough space to show the last row of suggestions. I'm guessing it has something to do with something else in my `init.el` file that is interfering with the display, but can't think of what that might be. At any rate, I'm sure it is something I can live with.

<img width="897" alt="Screen Shot 2020-12-25 at 3 08 36 PM" src="https://user-images.githubusercontent.com/1924526/103141515-2350d880-46c3-11eb-9bea-3b4539b1f18b.png">

**Comment by rougier** [comment]
I just tested and I got the same (first and second typo). If you remove the spaces from modeline the problem dissappears but the modeline is smaller. I could use a box instead of spaces but then I cannot have the white outline around the header line.

**Comment by dixius99** [comment]
So I'm not sure what to do with this issue. I feel that it's not a problem for the vast majority of the time, and also that it's something you might try to address at some time down the road, if inspiration strikes. Should I close the issue?

**Comment by rougier** [comment]
You can leave it open as a reminder this is to be fixed. And thank for the report.

**Comment by lduktus** [comment]
I am little bit late to this. As I am pretty new to emacs I don't think that I am really able to contribute something, however I had some thoughts I wanted to share (not sure it is the right way to do it or if I should open a new issue for this one). Maybe it would be interesting to add a functionality to nano-emacs to disable the Modeline for certain windows?
Another aspect would be to add some functionaity to control where certain types of windows spawn? I know there is popwin, which does something similar. After reading a little bit into the topic, it does seem kind of "hacky". Imo this would make the whole experience a little bit more streamlined. However not sure if it is to much work or "out of scope". I just wanted to share the idea.

Thanks for the great work, it was and is also very helpfull for learning some elisp and emacs in general.

**Comment by rougier** [comment]
Thanks for the suggestion. Best would be to open a new issue with these suggestions such that we can start a discussion.

**Comment by lduktus** [comment]
You can try to customize ispell-choices-win-default-height. At least to me it seems to work.

**Comment by aaronjensen** [comment]
For me, this https://github.com/aaronjensen/nano-modeline/commit/e806dea976a81639b14d13f83f9194619fbf7d71 plus setting `ispell-choices-win-default-height` to 3 fixed it.

**Comment by rougier** [comment]
@aaronjensen I think this might be the best we can do. Could you make a pull request at https://github.com/rougier/nano-modeline? (after having signed the copyright form at https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html)

**Comment by aaronjensen** [comment]
@rougier I've got my copyright assignment already, but I don't know when I'll be able to open a PR for this. I use a fork of nano-modeline now-a-days. Feel free to use the above code or any derivative. Thank you.

**Comment by rougier** [comment]
I can wait for your PR or I'll integrate your code, as you prefer. Just tell me.

**Comment by aaronjensen** [comment]
Please feel free to integrate my code. Thank you!

**Comment by rougier** [comment]
Done!
