### ISSUE TITLE
[Question] Automatic preview of text formatting org-mode

### ISSUE THREAD

**Issue by Ieremies** [rougier/nano-emacs#40]
So, I'm just started my journey in Emacs, and I've been loving nano! Recently I realized that somehow the org-mode text formatting like `=verbatin=` was shown as 
![image](https://user-images.githubusercontent.com/36969625/103354324-06812000-4a8a-11eb-9f39-2752bab2b534.png)

How do I disable this behavior? I do have some programming experience but my elisp skills are almost none.

**Comment by jpablobr** [comment]
For that you can set the following Org variable to nil:

```elisp
(setq org-hide-emphasis-markers nil)
```

Basically the opposite of this question:
https://stackoverflow.com/questions/10969617/hiding-markup-elements-in-org-mode

**Comment by Ieremies** [comment]
Thanks sooo much!
