### ISSUE TITLE
extend face attribute breaks on emacs 26 using org

### ISSUE THREAD

**Issue by sr105** [rougier/nano-emacs#41]
Emacs throws an error for the unknown face attribute in nano-theme.el.
Seems like a bug that emacs created: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=37774

Solution: I upgraded my emacs from 26.3 to 27.

**Comment by E3D3** [comment]
same here, but I can't upgrade my Emacs.

**Comment by rougier** [comment]
Thanks or the report, it has been fixed (with a conditional test on the version).
