### ISSUE TITLE
Buffer switching buttons have disappeared with recent updates

### ISSUE THREAD

**Issue by dixius99** [rougier/nano-emacs#42]
Not sure what's causing this, but with the latest updates from the last few days, the buffer-switching buttons have disappeared. Here's what I would see with `emacs -q -l nano.el` using the master as of around 10 days ago:
<img width="808" alt="Screen Shot 2020-12-30 at 2 51 02 PM" src="https://user-images.githubusercontent.com/1924526/103378131-4e666e00-4aaf-11eb-8f6f-f42efb826946.png">
And here I what I see with master as of this morning:
<img width="808" alt="Screen Shot 2020-12-30 at 2 50 40 PM" src="https://user-images.githubusercontent.com/1924526/103378156-64742e80-4aaf-11eb-8925-c59021662b31.png">
In the latest updates, the divider line at the bottom of the frame also looks different (in my opinion, nicer).

Not sure exactly what would be causing the mode line buttons to disappear though.

**Comment by rougier** [comment]
I removed the buttons indeed because I thought they were not super useful.

**Comment by dixius99** [comment]
Ah, that explains it 🤓

I don't think I ever really used them, though they did look nice 👍
