### ISSUE TITLE
Install with straight.el

### ISSUE THREAD

**Issue by Linuus** [rougier/nano-emacs#43]
I tried to install with [straight.el](https://github.com/raxod502/straight.el) but I'm not sure how to... Maybe someone has successfully installed it with straight?

What I've tried is:

```elisp
  (use-package nano-emacs
    :straight (:host github :repo "rougier/nano-emacs")
    :demand t)
```

Which gives the error:

```
error: nano-writer.el:0:0: error: scan-error: (Unbalanced parentheses 2898 4298)
```

I assume I'm just doing something wrong here.... maybe someone can point me in the right direction?

**Comment by rougier** [comment]
There was a missing paren in the mode. I've just fixed it, can you give a retry?

**Comment by Linuus** [comment]
Sure. It looks like I'm getting a bit further now at least! 

With this:

```elisp
  (use-package nano-emacs
    :straight (:host github :repo "rougier/nano-emacs")
    :demand t
    :config
    (nano-faces)
    (nano-theme))
```

I get `Error (use-package): Cannot load nano-emacs` though. I've tried to get some more debug info but to no success 🤔  Will try more a bit later.

**Comment by Linuus** [comment]
Ah it tries to load a a package named `nano-emacs` but there is no such file. I’ll just remove the demand and require the files manually. It should work :)

**Comment by bakirtzisg** [comment]
@Linuus Could you post a full solution? This is my current problem with trying straight and NΛNO. See https://github.com/rougier/nano-emacs/issues/37

**Comment by Linuus** [comment]
I change my mind and kept doom-nord instead, but something like this:

```elisp
  (use-package nano-emacs
    :straight (:host github :repo "rougier/nano-emacs")
    :config
    (require 'nano-faces)
    (require '....)
    (nano-faces))
```

I think you need to require stuff in the correct order etc. or it might not work.

**Comment by WillPower3309** [comment]
Anyone looking for this still, here is what I do:
```
(straight-use-package
 '(nano-emacs :type git :host github :repo "rougier/nano-emacs"))
```

from here, just paste the `nano.el` contents below. My personal config is as follows:
```
(straight-use-package
 '(nano-emacs :type git :host github :repo "rougier/nano-emacs"))

(require 'nano-theme-dark)

(require 'nano-faces)
(nano-faces)

(require 'nano-theme)
(nano-theme)

;; Nano header & mode lines
(require 'nano-modeline)

;; Welcome message
(let ((inhibit-message t))
  (message "Welcome to GNU Emacs / N Λ N O edition")
  (message (format "Initialization time: %s" (emacs-init-time))))

(require 'nano-splash)
```

**Comment by rougier** [comment]
Maybe this should go to the README or an INSTALL file. Anyone willing to make a PR?

**Comment by WillPower3309** [comment]
> Maybe this should go to the README or an INSTALL file. Anyone willing to make a PR?

I can! It works seamlessly with a couple of caveats that are important to note

**Comment by caleb** [comment]
I got nano working with use-package.... the issue was that the package name was just `nano` and not `nano-emacs`

**Comment by wunki** [comment]
In the end, this is what I ended up doing:

``` elisp
(use-package nano-emacs
  :no-require t
  :straight (:host github :repo "rougier/nano-emacs")
  :defines (nano-font-family-monospaced nano-font-size)
  :config
  (setq nano-font-family-monospaced "Berkeley Mono")
  (setq nano-font-size 19)
  (require 'nano))
```
