### ISSUE TITLE
Segmentation Fault when using nano-layout

### ISSUE THREAD

**Issue by jacksonludwig** [rougier/nano-emacs#52]
Weirdly, when requiring nano-layout in my own config, I get a segmentation fault and emacs crashes on startup. 
Using the example config with -q works, though. Also, all other modules don't seem to cause any issues. Any idea what this could be about?

**Comment by jacksonludwig** [comment]
My fault I think, I forgot to reload my font cache after installing fira code.

**Comment by rougier** [comment]
You mean you got a segfault because of a font cache problem? That sounds pretty extreme from emacs.

**Comment by jacksonludwig** [comment]
@rougier I thought so too... maybe it wasn't that exactly, but it was consistently segfaulting before that only when using the layout module. The only thing I remember doing that changed it was rebuilding the font cache.
