### ISSUE TITLE
Question about contributing

### ISSUE THREAD

**Issue by cmacrae** [rougier/nano-emacs#53]
Hey @rougier 👋 

I've been working on adding support for a few packages that I use across a few branches of [my fork](https://github.com/cmacrae/nano-emacs) which I'm intended to raise PRs for.  
Some not finished and certainly more to come, but I wanted to ask what your preference would be around the approach for some of these.  

For instance, in my branch to support Neotree, I've implemented conditional all-the-icons and projectile support so it looks like this:
<img width="299" alt="image" src="https://user-images.githubusercontent.com/3392199/105634225-ef4d0c80-5e54-11eb-9979-5f1bac1550eb.png">

It will fallback to no icon and the directory name instead of project, but; would you generally prefer to keep this sort of logic out of the main theme?

**Comment by rougier** [comment]
Hi @cmacrae. Thanks for this nice work and I think the easiest would be to have a `nano-tree.el` and have the default fallback as you propose. The idea behind nano-emacs is to reduce dependencies to a minimum (or none at all) such that people can re-use one the sub-module without too much hassle. So I think your fallback approach would fir perfectly (with some documentation in the header maybe).

Maybe at some point an org documenation wou be necessary to explain modules and how to contribute.

**Comment by cmacrae** [comment]
Okay, great - creating a dedicated elisp file is a good shout 👍   
I like the idea of an org doc, too :) 

I'll close this off. You can expect some contributions soon!
