### ISSUE TITLE
bold font not working in org & md

### ISSUE THREAD

**Issue by BeneathCloud** [rougier/nano-emacs#54]
In a `emacs -Q -l nano.el`, the bold font in org-mode or markdown-mode doesn't work, it just seems like a normal font without any bold.

I am using macOS and the Roboto Mono font is installed.

The "bold" is actually "\*bold\*", which is hided because of `org-hide-emphasis-markers`:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/19836675/107343317-8cba6880-6b04-11eb-9b69-8a4a958f0029.png">

**Comment by rougier** [comment]
I have the same problem actually on OSX. I already filled a bug but didn't hear about since then.
A tempory fix is to create a specific font with only one weight, one for light and one for medium. I can send them to you if you want.

**Comment by BeneathCloud** [comment]
@rougier Thank you! your tempory fix is working, now I get a bold font finally.
This seems like an emacs problem, it doesn't read all weights, just choose several of them.

**Comment by rougier** [comment]
Do you know by any chance what is the change in Big Sur that leads emacs to be confused?

**Comment by BeneathCloud** [comment]
Sorry I have no idea why, but someone seems to have reported this bug [bug#46436: 27.1.91; Font weight issue on MacOS Big Sur](https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-02/msg00754.html)

**Comment by dangom** [comment]
Hi guys, is there a current recommended solution for this issue?! Would love to get the bold font working as well. :)

**Comment by rougier** [comment]
I'm splitting the font file into several weights using [fonttools](https://arrayofcode.com/extract-font-names-from-otf-ttf-woff-woff2-files-in-python-using-fonttools/) and specify them in my .emacs.

**Comment by dangom** [comment]
Yes - I'm currently doing the same. Added some instructions for that on [my fork](https://github.com/dangom/nano-theme) of nano-theme, based on your suggestions, and updated the fonts on the theme respectively.

**Comment by rougier** [comment]
Let's hope the OSX version is fixed with Emacs 28 release.
