### ISSUE TITLE
Bold inside org-mode

### ISSUE THREAD

**Issue by gutofarias** [rougier/nano-emacs#58]
Hello, how are you?

**Even using the quick test** it seems that my face configuration for bold is the same as the default text, at least for org-mode. In org-mode the headings are not becoming any different and the \*bold\* doesn't also doesn't change the looks of regular text.
Is this a problem with my setup or a proper issue?

**Comment by rougier** [comment]
Hi @gutofarias. What is your os ? On OS Big Sur, there's a problem with fonts and Emacs and you need to hack nano setup.

**Comment by gutofarias** [comment]
It is indeed Big Sur! Is the hack easy? Could you guide me somehow in what to change?

**Comment by gutofarias** [comment]
Thank you! That worked! I had your article about text editors, very eye-opening! Congrats! I'm trying a lot of the stuff.. The only thing I have a doubt is about the syntax coloring.. If not abused I have the impression that it helps a lot!

**Comment by rougier** [comment]
Great ! For the syntax coloring, it might be a bit extreme but I get used to it now :)
