### ISSUE TITLE
Eshell doesn't launch with nano-emacs

### ISSUE THREAD

**Issue by jacksonbenete** [rougier/nano-emacs#6]
There is a problem, at least on my conf, that `eshell` doesn't works with `nano-emacs`.
I've traced the problem to the `(setq-default mode-line-format "%-")` on `nano-modeline.el`.

Commenting the line will cause eshell to run but will leave you with the vanilla modeline at bottom.
If you ever split the window, it will cause the hook at `(add-hook 'window-configuration-change-hook 'nano-modeline-update-windows)` to correct the modeline.

I'm working on it but I would like a confirmation if this is also happening with someone else as it can be just a conflict in my init.el calls.

**Comment by rougier** [comment]
Same for me. Not sure what causes this. Maybe eshell is intercepting the modeline `setq-default`.

**Comment by rougier** [comment]
It seems `(setq eshell-status-in-modeline nil)` (in nano-modeline.el) fixes the problem. It  would be nice to have a dedicated headerline for eshell though.
