### ISSUE TITLE
Nano-writer mode

### ISSUE THREAD

**Issue by vignesh-TG** [rougier/nano-emacs#60]
How to enable the nano-writer mode ?

**Comment by rougier** [comment]
You can first add a line in [nano.el](https://github.com/rougier/nano-emacs/blob/master/nano.el) to load the mode. Then, when editing an org file, you can type `M-x nano-writer-mode`

**Comment by vignesh-TG** [comment]
> You can first add a line in [nano.el](https://github.com/rougier/nano-emacs/blob/master/nano.el) to load the mode. Then, when editing an org file, you can type `M-x nano-writer-mode`

Thanks for the reply.

After Adding ` (require 'nano-writer)` to nano.el , I tried to load nano-writer mode I could not find the nano-writer mode.  I even tried `M-x load-library,` where I am able to load the nano-writer library but when try `M-x nano-writer-mode`, I do not find the nano-writer mode.

**Comment by rougier** [comment]
Sorry, it `writer-mode`

**Comment by vignesh-TG** [comment]
Thank you, it works !!
