### ISSUE TITLE
Should `org-return-follows-link` be set to `t`?

### ISSUE THREAD

**Issue by apc** [rougier/nano-emacs#62]
Thanks for your work on this terrific project. 

I suspect you have already considered this and rejected it, but in case you haven't: wouldn't it make sense to set `org-return-follows-link` to `t`? That way, especially when visiting the quick-help, newcomers will be more likely to realize you can make use of the links without using the mouse. (Not everyone will try `C-c C-o` with point on 'Full preferences', for example, but probably everyone familiar with using the keyboard to follow hyperlinks will try RET...)

**Comment by rougier** [comment]
Thanks. I think I initially set it to `t` and removed it for some reason I forgot. Can you make a PR?

**Comment by apc** [comment]
Sure, but a couple of questions first: would you want this as a default? Or just as a local variable in the help buffer? If the former, would this go in `nano-defaults.el`?

**Comment by rougier** [comment]
I think default would do. Experrienced user will know how to disable it while it may help new users as you explained.
