### ISSUE TITLE
Font ‘Roboto Mono Emacs Regular 14’ is not defined"

### ISSUE THREAD

**Issue by lg2011** [rougier/nano-emacs#7]
Thanks for your work to enhance the look and feel of emacs. 
I have a warning at startup "frame-notice-user-settings: Font ‘Roboto Mono Emacs Regular 14’ is not defined". I have the Roboto Mono font fully installed from the link provided in the README. Do I need to install other "Roboto" fonts ?

**Comment by rougier** [comment]
Sorry, this was a local hack to make it work on OSX BigSur. It should be fixed now.
