### ISSUE TITLE
Error when running `emacs -q -l nano.el` in Termux.

### ISSUE THREAD

**Issue by gh-name** [rougier/nano-emacs#70]
`Symbol’s function definition is void: tool-bar-mode`

Is this caused by any GUI options?
I tried to install Emacs with X, but it seems no longer seen as `x11-repo/emacs`.

```
window-system is a variable defined in ‘C source code’.
Its value is nil
It is a terminal-local variable; global value is the same.

  Probably introduced at or before Emacs version 21.1.

Documentation:
Name of window system through which the selected frame is displayed.
```

**Comment by dotpat** [comment]
If so, is there any chance to improve the error message when use without X, or enable this feature to run it in terminal?

**Comment by dotpat** [comment]
Confirmed. Arch Termux works.

**Comment by rougier** [comment]
Does it work if you comment out the faulty line?

**Comment by dotpat** [comment]
> Does it work if you comment out the faulty line?



> Does it work if you comment out the faulty line?

Just had a try. It can boot after commented out that line. And scroll-bar-mode also had the problem but without modify it can still boot unlike tool-bar.

**Comment by rougier** [comment]
So we can add a specific test before trying to disbale the tool-bar. For example `(if (fboundp 'tool-bar-mode) (tool-bar-mode nil))`

**Comment by gh-name** [comment]
> So we can add a specific test before trying to disable the tool-bar. For example
> 
> ```
> (if (fboundp 'tool-bar-mode) (tool-bar-mode nil))
> ```
> 
> Coud lyou try this line?

Works. May be same for scroll bar

**Comment by rougier** [comment]
Can you make a PR?

**Comment by gh-name** [comment]
> Can you make a PR?

my pleasure. I noticed that nix has `Emacs built without any dependency on X11 libraries. ` so I gonna test on both environments later.
