### ISSUE TITLE
Layout.el: Wrong Type Argument

### ISSUE THREAD

**Issue by WillPower3309** [rougier/nano-emacs#74]
In prep for my PR to add install instructions for nano through straight.el, the entire nano project can't be installed as `layout.el` brings up this error:

```
Wrong type argument: char-table-p, nil
```

One solution is to omit it and manually install all the other parts of nano through straight, and essentially recreate nano.el without straight.el (as I showed in my snippet from #43 ), but this takes away from the simplicity of the install

**Comment by rougier** [comment]
Thanks for the report. Do you know where the problem occurs in layout.el?

**Comment by WillPower3309** [comment]
No longer experiencing the error, I wonder if it was an error on my side thru straight.el, will update if it returns but closing for now
