### ISSUE TITLE
Nano Modeline incompatible with treemacs

### ISSUE THREAD

**Issue by WillPower3309** [rougier/nano-emacs#75]
When attempting to run `treemacs` with an emacs config that includes nano-modeline, `Wrong type argument: listp, ""` results

**Comment by WillPower3309** [comment]
Noticed that the modeline has checks for different buffer types, maybe a default value of not being displayed would work

**Comment by rougier** [comment]
Thanks for the report. You proposed fix might work actually. If treemacs has its own mode (I guess so), it's a matter of adding it to the nano-modeline list. But it shoudl use the default header line that seems to be wrong for some reason. Do you have any idea what could be wrong? Or, another way to debug would be to simplify the default modeline and check when it breaks.

**Comment by WillPower3309** [comment]
Commenting out line 518:
```
(setq-default mode-line-format "")
```
Fixes the issue

**Comment by WillPower3309** [comment]
Unsure as to why that is, as my emacs knowledge isn't too advanced, but I hope that helps

**Comment by rougier** [comment]
Oh, this is the mode line, not the header line actually. Even if we add a special case for treemacs-mode in nano-modeline, tit won't change the mode-line. Myabe you can try to comment the code at the bottom of nano-modeline that modify the mode-lien depending on surrounding windows.

**Comment by jdm204** [comment]
I have the same issue and the same fix (`;;(setq-default mode-line-format "")`) works for me with no noticeable side effects so far.

**Comment by rougier** [comment]
I pushed a change to remove a hook on the modeline that may fox the problem.

**Comment by WillPower3309** [comment]
> I pushed a change to remove a hook on the modeline that may fox the problem.

I'll check it out later today and confirm if it works!

**Comment by WillPower3309** [comment]
Unfortunately the problem still remains

**Comment by rougier** [comment]
Can you call `toggle-debug-on-error` and post the trace?

**Comment by rougier** [comment]
Sorry for late answer. Can you check with the nano-modeline on ELPA?

**Comment by WillPower3309** [comment]
I actually have issues with the nano-modeline from ELPA. Running `M-x nano-modeline-mode` results in:
```
Wrong number of arguments: (3 . 4), 2
```

I assume I may be calling it incorrectly?

Can verify I have the most recent version 0.5 as well from `M-x package-list-packages`
```
nano-modeline                  0.5            external              N Λ N O modeline
```

**Comment by rougier** [comment]
Sorry for late answer. What is `nano-mod`, is that one of your function? Alos, one way to test would be to open the nano-modeline.el file in an "Emacs -Q" session and to evaluate the buffer. This might avoid any interference with other packahges and could help to isolate the problem.

**Comment by WillPower3309** [comment]
Very sorry for the late update, the recent Elpa version now seems to be working
