### ISSUE TITLE
mu4e-moved-face undefined in mu 1.6.0

### ISSUE THREAD

**Issue by stopbystudent** [rougier/nano-emacs#96]
In July, mu 1.6.0 has been released (see [the release on GH](https://github.com/djcb/mu/releases/tag/1.6.0)). Part of the release has been the complete transition to the gnus-based message viewer as the default. In turn, some of the faces have vanished. One of them is `mu4e-moved-face` used in

https://github.com/rougier/nano-emacs/blob/6751b567626c81b77755259fc36c5838de65a6ba/nano-theme.el#L546

It seemed to be only defined in `mu4e-vars.el` and never used, at leat if my grepping through mu4e's sources at the 1.4.9 release (the one prior to 1.6.0) is correct. Some of the mu4e faces in `nano-theme.el` are similarly only defined somewhere but never used within mu4e.

However, the one thing that is preventing loading the complete `nano-theme.el` for me is that `mu4e-moved-face` is undefined. Maybe a version check for the mu4e version around the line in question could solve this?

**Comment by rougier** [comment]
Sorry for the delay. I've released [nano-theme](https://github.com/rougier/nano-theme) which is also available on ELPA. Hopefully, this bug has been fixed

**Comment by pmatos** [comment]
> > Sorry for the delay. I've released [nano-theme](https://github.com/rougier/nano-theme) which is also available on ELPA. Hopefully, this bug has been fixed
> 
> Still trying to setup `nano-theme`, however I am not confident this is fixed: https://github.com/rougier/nano-theme/blob/5aea8a100413ea1c9723b019cb3ce3bbbe5a0302/nano-theme.el#L999

Unsure what's happening and why we don't hit the same problem, but nano-theme is working without issues. Thanks.

**Comment by rougier** [comment]
nano-theme is the recommended version. I need to update the README in nano-emacs to explain that packages are now available individually.
