### ISSUE TITLE
Initial install on Windows doesn't look right

### ISSUE THREAD

**Issue by olegbc1** [rougier/nano-emacs#98]
Screenshot below. This is vanilla emacs 27.1 init.el on Windows 10. After bootstrapping and installing straight.el and installing nano, for some reason the `scroll-bar-mode`, `toll-bar-mode`, and `menu-bar-mode` are all showing up whether or not I set them to `-1` 

Thank you!

![image](https://user-images.githubusercontent.com/9222334/135029313-77452b31-bc18-4ea9-abc8-dd20c9c622f1.png)

**Comment by rougier** [comment]
Are you able to hide them without nano-emacs ?

**Comment by olegbc1** [comment]
yeah, these elements are hidden in my `init.el` via
```
(scroll-bar-mode -1)        ; Disable visible scrollbar
(tool-bar-mode -1)          ; Disable the toolbar
(tooltip-mode -1)           ; Disable tooltips
```
but they show up when I enable nano-emacs.

**Comment by rougier** [comment]
Can you give at [nano-theme](https://github.com/rougier/nano-theme) ? It's on ELPA.

**Comment by azzamsa** [comment]
Same issue here. 

> Can you give at [nano-theme](https://github.com/rougier/nano-theme) ? It's on ELPA.

Would you like to elaborate more?
You mean try using only the nano theme instead all config?

**Comment by azzamsa** [comment]
@olegbc1 I can get it working correctly using the following config:

```lisp
(straight-use-package
  '(nano-emacs :type git :host github :repo "rougier/nano-emacs"))

(use-package nano-base-colors :straight nil)
(use-package nano-colors :straight nil)
(use-package nano-theme-light
  :straight nil
  :config
  (nano-theme-set-light))

(use-package nano-faces
  :straight nil
  :config
  (nano-faces))

(use-package nano-theme
  :straight nil
  :config
  (nano-theme))

(use-package nano-modeline
  :straight nil)
```

credit: https://github.com/spac3c4det/.emacs.d/blob/c721982e0f3c4cab333b3a496c0a1c3936dad6f8/straight/repos/nano-emacs/nano.el#L8

**Comment by azzamsa** [comment]
This fixes my issue:
- https://github.com/rougier/nano-emacs/pull/107

**Comment by rougier** [comment]
Thanks, it has been merged.
